const assert=require('node:assert/strict');
require('./detector.js');
const D=global.EgitimDetector;
const bar={innerText:'00:24 / 05:14 6 / 22'};
const next={parentElement:bar};
let color='rgb(73, 71, 90)';
global.getComputedStyle=()=>({backgroundColor:color});
assert.equal(D.barReady(next,bar),false);
color='rgb(218, 47, 92)';
assert.equal(D.barReady(next,bar),false,'red before duration ends cannot advance');
bar.innerText='01:39 / 01:39 4 / 22';
color='rgb(73, 71, 90)';
assert.equal(D.barReady(next,bar),false,'timer alone cannot advance');
color='rgb(218, 47, 92)';
assert.equal(D.barReady(next,bar),true);
color='rgb(73, 71, 90)';
assert.equal(D.barReady(next,bar),true,'retain blink signal for same completed page');
bar.innerText='00:00 / 01:39 5 / 22';
assert.equal(D.barReady(next,bar),false,'new page resets completion');
assert.equal(D.timerDone('00:00 / 00:00'),false);
console.log('Timed red-arrow completion checks passed');
const imageArrow={id:'gonextImage',tagName:'IMG',title:'Sonraki Sayfaya Git'};
assert.equal(D.findBarNext({querySelector:selector=>selector==='#gonextImage'?imageArrow:null},()=>true),imageArrow,'image navigation recognized without button role or tabindex');
assert.equal(D.findBarNext({querySelector:()=>imageArrow,querySelectorAll:()=>[]},()=>false),null,'hidden arrow ignored');
